# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            REST Fest Videos Project
tagline:          'All the REST Fest on film.'
description:      'All the REST Fest on film.'
#url:              http://videos.restfest.org
#baseurl:          /
author:
  name:           'BigBlueHat'
  url:            http://bigbluehat.com/
repository:       restfest/videos.restfest.org

paginate:         5

collections:
  videos:
    output: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/BigBlueHat/videos.restfest.org

# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jemoji
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - lib/semantic
  - node_modules
  - semantic.json
  - LICENSE
  - README
  - scripts/

jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: tag-archive
